language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - composer install

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-text; fi
